# Operating system (build VM template)
os: Visual Studio 2015

platform: x64

clone_folder: c:\gopath\src\github.com\minio\minio

# environment variables
environment:
  GOPATH: c:\gopath
  GO_EXTLINK_ENABLED: 0
  GO15VENDOREXPERIMENT: 1
# Remove this after fixing erasure code.
  GODEBUG: cgocheck=0

# scripts that run after cloning repository
install:
  - '"C:\Program Files\Microsoft SDKs\Windows\v7.1\Bin\SetEnv.cmd" /x64'
  - curl -fsSL -o c:\go\bin\yasm.exe http://www.tortall.net/projects/yasm/releases/yasm-1.3.0-win64.exe
  - set PATH=%GOPATH%\bin;c:\go\bin;%PATH%
  - rd C:\Go /s /q
  - appveyor DownloadFile https://storage.googleapis.com/golang/go1.6.windows-amd64.zip
  - 7z x go1.6.windows-amd64.zip -oC:\ >nul
  - curl -fsSL -o mingw-w64.7z http://downloads.sourceforge.net/project/mingw-w64-dgn/mingw-w64/mingw-w64-bin-x86_64-20151206.7z
  - 7z x -oC:\ mingw-w64.7z > NUL
  - set PATH=C:\mingw64\bin;%PATH%
  - x86_64-w64-mingw32-gcc --version
  - go version
  - go env
  - git clone https://github.com/minio/isa-l
  - cd isa-l
  - make -f Makefile.unx arch=mingw
  - mv include isa-l
  - set CGO_CPPFLAGS=-Ic:/gopath/src/github.com/minio/minio/isa-l
  - set CGO_LDFLAGS=c:/gopath/src/github.com/minio/minio/isa-l/isa-l.a
  - set CC=x86_64-w64-mingw32-gcc
  - set CXX=x86_64-w64-mingw32-g++
  - cd %GOPATH%\src\github.com\minio\minio

# to run your custom scripts instead of automatic MSBuild
build_script:
  - go generate github.com/minio/minio/pkg/crypto/sha1
  - go test .
  - go test -race .
  - go test github.com/minio/minio/pkg...
  - go test -race github.com/minio/minio/pkg...
  - go run buildscripts/gen-ldflags.go > temp.txt
  - set /p BUILD_LDFLAGS=<temp.txt
  - go build -ldflags="%BUILD_LDFLAGS%" -o %GOPATH%\bin\minio.exe

# to disable automatic tests
test: off

# to disable deployment
deploy: off
