site_name: Minio Documentation
pages:
- ['index.md', Welcome to Minio]
- ['introduction.md', Minio API Reference]
- ['api/minio.md', 'API', 'REST API']
- ['api/errors.md', 'API', 'Error Responses']
- ['api/manage.md', 'API', 'Management']
- ['architecture.md', 'Architecture', 'Overview']
- ['contributing.md', 'Contributing', 'Overview']
theme: readthedocs
