site_name: Minio Documentation
pages:
- ['index.md', Welcome to Minio]
- ['architecture.md', 'Minio', Architecture]
- ['contributing.md', 'Minio', Contribute]
- ['introduction.md', 'API', Reference]
- ['minio.md', 'API', REST API]
- ['errors.md', 'API', Error Responses]
- ['manage.md', 'API', Management API]
theme: readthedocs
